RopeWiki/app

webserver/html/ropewiki/LocalSettings.php

This renames the edit tabs from "Edit with Form" and "Edit", to "Edit" and "Edit Source". This change in naming more accurately reflects the editing mode that the lay user can expect.

Rename Edit tabs

---

deploy_tool.py
docker-compose.yaml
webserver/Dockerfile

This PR adds `codebase_version.html` to the root of the webserver and populates it with information regarding how the webserver image was built when deploy_tool.py is used to perform actions on the site.  Implements #8.  See an example of `codebase_version.html` on [the staging server](https://dev.ropewiki.com/codebase_version.html).

Add codebase_version.html to webserver

---

deploy_tool.py
reverse_proxy/services.conf

This PR adds a 301 redirect from a `www.`-prefixed hostname to the plain hostname (`WG_HOSTNAME`).  This is intended to cause www.ropewiki.com to behave like ropewiki.com, but I have not tested it as my dev server setup uses a different reverse proxy.

Add second server name for www prefix

---

webserver/html/ropewiki/LocalSettings.php

en_US.utf8 is the current setting and it is not installed on the server, however C.UTF-8 is installed and it solves the problem of creating thumbnails with accented characters.
See this link for more info:
https://www.mediawiki.org/wiki/Manual:Common_errors_and_symptoms#Image_Thumbnails_not_working_and/or_appearing:~:text=When%20the%20path%20is%20missing%20non%2DASCII%20characters

Update ShellLocale to an available locale

---

docker-compose.yaml

Just a very minor quality-of-life fix.
Noticed the containers don't set their hostname, so when you ssh into them you don't get a nice prompt confirming which one you've accessed.
e.g.
```
[...]
Last login: Thu May 11 07:13:07 2023 from 75.172.120.71
backupreader@8ce4ef5ab64f:~
```
Now it should appear:
```
backupreader@ropewiki_db:~
```

Add hostnames to containers

---

database/Dockerfile
database/backup.cron
database/scripts/backup_mysql.sh
database/scripts/system_start.sh
docker-compose.yaml
webserver/Dockerfile

- Backups actually run automatically (starts cron)!
- Fixes path to SQL_BACKUP_FOLDER (i.e. backups now persist outside the container).
- Adds logging (size, time, etc) to `backup.log`.
- Touches `last_success` file for future monitoring.
- Improves timestamp in backup filename (`2023-05-13-181803`) so that there can be more than one backup a day.
- Add a killswitch to stop backup (`/do_not_backup_db`), e.g. during development 
- Install `rsync` and `less` in the containers.
Example log entry (of minimal database):
```
=== Sun May 14 06:21:01 UTC 2023 ===
Starting backup to /home/backupreader/backups/all-backup-2023-05-14-062101.sql.gz
mysqldump: [Warning] Using a password on the command line interface can be insecure.
real    0m0.222s
user    0m0.207s
sys     0m0.015s
-rw-r--r-- 1 root …
```

Fix DB Backups! 🤩

---

deploy_tool.py
docker-compose.yaml
mailserver/Dockerfile
mailserver/README.md
webserver/Dockerfile
webserver/html/ropewiki/LocalSettings.php

While https://github.com/RopeWiki/app/pull/26 technically worked - the realities of the internet in 2023 mean many hosting companies simply do not want you hosting your own mailserver. So this is a do-over using gmail's smtp relay instead.
Lots of details in the readme.
I've tested it with my own credentials (which I can share if people want to test with), but in production it will need to be provided with ropewiki@gmail.com's smtp password (link to a setup guide in the readme).

SMTP mail relay & mediawiki config 📧2️

---

docker-compose.yaml

I think this bug sneaked in when I accepted the suggest change directly on github. These values needs to be unquoted to work in the postfix config correctly.

Unquote smtp username & password vars

---

deploy_tool.py

This adds a safety check when restoring the database.
I've done Ctrl+R to rerun a deploy_tool command and accidentally ran restore_db, which immediately wipes out the current db without any chance to abort.
Confirmed it works for both `restore_empty_db` and `restore_db`.
```
./deploy_tool.py ak restore_empty_db
Restore /mnt/data/containers/ropewiki/database/empty_schema.sql? (y/n): n
2023-06-07T19:54:31.040363 Aborting restore
```

Ask for confirmation before restoring db

---

webserver/Dockerfile
webserver/html/ropewiki/LocalSettings.php

This extension is included by default in MediaWiki versions 1.31 and above. It allows sitewide text replacement for bureaucrat level users and above.

Add ReplaceText extension

---

publish.sh

This simple script partially automates the process of publishing the Docker Hub images of a new release.  It has not yet been tested as written, though the commands are hopefully copied in faithfully from a successful published release.

Add release publishing script

---

README.md
deploy_tool.py
docker-compose.yaml

This resolves #35 by removing all use of docker-compose v1 in favor of the docker compose v2 plugin.  Tested locally on a Windows machine by bringing up a system to the point of enabling TLS (but not enabling TLS), verifying site functionality, then turning down.

Use docker compose v2

---

backup_manager/Dockerfile
backup_manager/scripts/backup_mysql.sh

In summary this is a super easy way of making our backups a lot smaller.
More details are explained here: https://github.com/RopeWiki/app/issues/31

Switch backups to use zstd rather than gzip

---

webserver/scripts/system_start.sh

Quick hack for the search index startup problem.
`searchd` starts really quickly, causing a race condition with the indexes being created...
```
precaching index 'wiki_main'
WARNING: index 'wiki_main': preload: failed to open /var/data/sphinx/wiki_main.sph: No such file or directory; NOT SERVING
precaching index 'wiki_incremental'
WARNING: index 'wiki_incremental': preload: failed to open /var/data/sphinx/wiki_incremental.sph: No such file or directory; NOT SERVING
FATAL: no valid indexes to serve
```
So just pause 2 seconds.

Pause between creating search indexes and starting searchd

---

publish.sh

Refactored `publish.sh` a bit so it's easier to understand.
I couldn't find a nice way to do the git tagging part locally (since it's using the http:// git end point, and keeps asking for a password - rather than the ssh:// one). So I just made it print the commands needs to be run elsewhere.
Tested by manually copying over to production and running it.
```
root@ropewiki:/rw/app# ./publish.sh
./publish.sh: line 6: 1: This script expects a version tag as the first argument. Run git tag to see current version tags.
root@ropewiki:/rw/app# ./publish.sh v1.3.0
The push refers to repository [docker.io/ropewiki/backup_manager]
286048513ca4: Layer already exists
61eb4cba0590: Layer already exists
025e024c0a86: Layer already exists
1ef4beed1a0a: Layer already exists
[...]
2033b354d55b: Layer …
```

Improvements to `publish.sh`

---

webserver/html/ropewiki/LocalSettings.php

Error logs are currently full of spam. This fixes the two main sources of it.
1. Conditionally set `REMOTE_ADDR `only if `HTTP_X_FORWARDED_FOR `is actually set.
2. Define `egMapsGMaps3ApiKey` & `egMapsGMaps3ApiVersion` even if we're not going to use them (see the linked discussion).
Testing:
- Ran locally, log spew stopped as expected. Also manually applied on prod webserver to confirm, also stopped as expected.

Remove a bunch of log spew

---

database/Dockerfile

These settings were suggested by mysqltuner.pl and have been active on the production database for >24hrs.
The database is stable, and *seems* to be performing better (i.e. load is significantly down) - but things were also added to the ip block list at the same time, so cause isn't 100% clear.
Tested docker changes locally, and config + tooling appears as expected.

Adjust mysql settings + add tools

---

docker-compose.yaml
reverse_proxy/Dockerfile
reverse_proxy/nginx.conf
reverse_proxy/scripts/system_start.sh
reverse_proxy/services.conf

- create a new volume for the proxy logs, mounted as `/logs`
- change nginx log location to use the volume
- change log format to the standard "combined" format rather than a customer one (to make parsing much easier).
- install the `goaccess` package (+ other useful tools)
- setup two new nginx endpoints, one to server the static html of `goaccess`, and another to handle its websocket for live updates.
- minor tweaks to nginx config (whitespace, automatically pick number of workers based on number of cpus).
Note: these logging changes mean nginx will no longer log to stdout, which means `docker log` will not show the logs. This isn't actually a big problem, as `docker logs` on kept 10M of logs anyhow. This now matches what the webserver container does too.
Testing: tested locally. Also …

nginx log changes & `goaccess` log parsing

---

webserver/robots/robots_prod.txt

These are two frequently seen bots which we can live without indexing the site.

Add Amazonbot & SeekportBot to robots.txt

---

reverse_proxy/blockips.conf
reverse_proxy/services.conf

This extends our blocking to drop requests for specific known bad URLs we shouldn't waste any cpu cycles processing.
Watching the logs, requests for these come in a few times a minute.
Examples of bad urls:
- bots exploiting pages which fetch external content:
```
GET /Weather?location=http%3a%2f%2fleewhan.com%2Fbbs%2Fboard.php
GET /Weather?location=http%3a%2f%2fbethongkongpools.com
```
- bots scanning for vulnerable wordpress endpoints:
```
GET /xmlrpc.php
GET /wp-login.php
```
We return a HTTP 444, which is a specific nginx code that drops the connection without sending a response (why should we even respond to known malicious traffic!).
Tested locally & manually in production. Results when fetching a blocked URL:

Add blocklist of known bad URLs

---

webserver/html/ropewiki/LocalSettings.php

- autoformat tabs (yuck) to spaces (for winners).
- only give mediawiki the first IP if there are multiple IPs present in the X-Forwarded-For header. This happens when people's traffic is being proxied (i.e. by their office) before reaching ropewiki.
Already hot-fixed on the production site. Fix confirmed as work by Ian who reported it: https://www.facebook.com/groups/ropewiki/posts/3454067094806607/

Stop mediawiki from being given multiple IPs in x-forwarded-for

---

webserver/scripts/system_start.sh

The site has been using out-of-the-box php configuration. To help site performance these can be improved.
- Increase php workers up to a max of 16. We have some mediawiki queries which are just naturally slow, so having very few workers meant easier requests were getting back logged.
- Enable the php opcache
>  OPcache improves PHP performance by storing precompiled script bytecode in shared memory, thereby removing the need for PHP to load and parse scripts on each request. 
Both these options have been tested locally and in production to see their effect. The chosen values are not crazy, but can be tweaked again in  future.

Optimize php config

---

reverse_proxy/blockips.conf
reverse_proxy/services.conf

Getting pretty sick of seeing the same user agents hammering away at the site - and chasing IP addresses is futile in the long run.
Lets get more serious and just drop requests from the worst user agents.
Tested by hot-fixing into production and checking the logs...
Request from Amazonbot being returned a 444
```
23.22.35.162 - - [18/Aug/2023:19:27:39 +0000] "GET /index.php?action=edit&redlink=1&title=File_talk:Little_Bighorn_Canyon.kml HTTP/1.1" 444 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/
support/amazonbot)"
```
Whereas other requests being handled like normal.

Add user-agent blocking to the reverse proxy

---

docker-compose.yaml

Despite `ufw` not allowing port 8080 from the internet, Docker adds its own iptables rules to permit any exposed container ports.
This is a problem because we've been hit by bots directly on port 8080, which bypass protections the reverse proxy provides.
So this PR is the real fix - no longer expose the port.
On the internal network the reverse proxy can still access the web server fine on port 80.
```
~: iptables -L -n -t nat
Chain DOCKER (2 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.19.0.5:80   <--- the bad line.
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp …
```

Remove port 8080 from webserver container

---

reverse_proxy/blockips.conf
webserver/robots/robots_prod.txt

This cleans up a few bot related things.
- Remove the google block. (2 people have asked me what's recently happened to ropewiki's google results as they've gone to crap, whereas duckduckgo is still good - this explains why).
- Move Yandex & Semrush blocks from IP to more robust useragent block
- Seekport is a nice bot and follows robots.txt since they were added there.
- Amazon is already blocked by useragent so no need for IP block
- The MS/Bing bots have switches to different IPs and already bypassed the IP-block and crawling the site. I also thing allowing Bing to crawl is an ok idea - weirdly people do actually use it.
Also adds the `crawl-delay` option to tell good bots to back-off a bit (one request per 5 seconds).
Deployed locally and confirmed all services start up correctly.

Update bot protections

---

webserver/Dockerfile
webserver/html/ropewiki/LocalSettings.php

Further work to improve site performance. This time by enabling php's in-memory key value store.
The mediawiki docs related to this: https://www.mediawiki.org/wiki/Manual:Performance_tuning#Object_caching
Page load times do seem to come down by about half a second with this enabled.

Enable php-apcu caching (per mediawiki docs)

---

webserver/html/ropewiki/LocalSettings.php
webserver/robots/robots_prod.txt

This makes actions use the same short URLs as viewing pages do.
This makes things a lot neater, and also tidies up SEO, as we don't have pages being indexed via two different URLs.
Tested locally, screenshots attached. Followed these instructions: https://www.mediawiki.org/wiki/Manual:$wgActionPaths
Example:
* Before:
https://ropewiki.com/index.php?title=Lewis_River&action=formedit
* After:
https://ropewiki.com/Lewis_River/formedit

Make page actions use short urls (`/edit`, `/history`, etc).

---

deploy_tool.py

#30 added the `--all-databases` flag to the backup manager (which is a good thing).
However it means the restore tool needs access to more than just the ropewiki db to restore the full backup.
```
ropewiki2:/rw# ./deploy_tool.py ak restore_db
Restore /rw/mount/sqlbackup/all-backup-2023-09-04-100002.sql? (y/n): y
2023-09-06T03:35:00.944603 Ensuring backup manager is available...
2023-09-06T03:35:00.944712   RUN git log -n 1
2023-09-06T03:35:00.954695   RUN git status
2023-09-06T03:35:00.958578   SCRIPT docker compose -p ak up -d ropewiki_backup_manager
2023-09-06T03:35:00.958602   RUN sh /rw/docker_compose_command.sh && rm /rw/docker_compose_command.sh
[+] Running 2/0
✔ Container ak-ropewiki_db-1              Running
✔ Container ak-ropewiki_backup_manager-1  Running
0.0s …
```

Switch db restore user from ropewiki to root

---

webserver/Dockerfile
webserver/html/ropewiki/LocalSettings.php

I strongly suspect the site ran with a higher upload limit in the past, but we've been using the php default since migrating the backend infra (2MB).
Let's make it something sensible for 2023 (10MB).
Tested locally:

Increase file upload limit

---

docker-compose.yaml

The db container stopped (for a yet undetermined reason). Had it been set to auto restart the site would have stayed online :-)
The `unless-stopped` stopped option means you can manually stop containers with docker restarting them later.

docker containers should restart unless explicitly stopped

---

database/Dockerfile
webserver/Dockerfile

These are settings I've already applied in production to help fix the weird php stalling issue, which we have to solve by restarting php-fpm.
```
emergency_restart_threshold
emergency_restart_interval
process_control_timeout
request_terminate_timeout
process_idle_timeout
```
It also enabled the mysql slow query log, so we can identify heavy weight queries.

Tweaks to help troubleshoot php-fpm stalling issue

---

webserver/Dockerfile

Argh. The previous logic didn't handle when the config options were commented out originally. So the options weren't actually being enabled!
Re-tested with a fresh container...
```
root@ropewiki_webserver:/# grep -vP '(^;|^$|^[[:space:]]+$)' /etc/php/5.6/fpm/pool.d/www.conf
[www]
user = www-data
group = www-data
listen = /run/php/php5.6-fpm.sock
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 16
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
request_terminate_timeout = 30s
```
```
root@ropewiki_webserver:/# grep -vP '(^;|^$|^[[:space:]]+$)' /etc/php/5.6/fpm/php-fpm.conf
include=/etc/php/5.6/fpm/pool.d/*.conf
[global]
pid = /run/php/php5.6-fpm.pid
error_log = /var/log/php5.6-fpm.log
emergency_restart_threshold = 10 …
```

Fix php config comments

---

webserver/Dockerfile

My investigations aren't turning up anything concrete, so adding a remediation to keep the site online.
Testing: this branch is already checked-out and production, and `docker inspect` shows the new heathcheck options.

webserver docker healthcheck

---

fpm-pool.conf
reverse_proxy/scripts/system_start.sh
webserver/Dockerfile

* Change the repo for `Preloader` module from `troyengel/Preloader` to a forked mirror at `nornagon/Preloader` (old repo went offline and broke container building).
* Update the php-fpm config (`pool.d/www.conf`) with recent changes to help stability (and give it a dedicated file rather than `sed`ing the config line by line).
* Disable `goaccess` to save a bit of CPU while the machine seem constantly busy.

Performance & Stability changes (and some repo housekeeping)

---

reverse_proxy/blockips.conf

These clients were being caught in our AWS blockage. Add a specific rule to allow them.

Allow luca/caltopo access from aws

---

reverse_proxy/Dockerfile
reverse_proxy/cloudflare.conf
reverse_proxy/nginx.conf
reverse_proxy/services.conf

These are all configs that have been active in production for anywhere between a day and 2 weeks.
This is housekeeping to ensure they're not lost :-)

Various nginx config tweaks (already in production)

---

webserver/robots/robots_prod.txt

Crawler’s are double-crawling the site because they visit the short URL and long URL, e.g.
https://ropewiki.com/Davis_Creek_Canyon
and 
https://ropewiki.com/index.php?page=Davis_Creek_Canyon
We should prefer the short version, and actually track down any places which are still using index.php in links.

Add “index.php” to robots.txt

---

backup_manager/Dockerfile
database/Dockerfile

The way apt handles signing keys has totally changed since the base image of this docker container was built, causing apt-update to fail, and hence container building to fail.
```
hcooper@rw:/containers/ropewiki/git/app$ docker run -it --network host mysql:5.7-debian bash
root@booty:/# apt update
[...]
Err:5 http://repo.mysql.com/apt/debian buster InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
[...]
Reading package lists... Done
W: GPG error: http://repo.mysql.com/apt/debian buster InRelease: The following signatures couldn't be verified
because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
E: The repository 'http://repo.mysql.com/apt/debian buster InRelease' is not signed.
N: Updating from such a …
```

Fix mysql repo key issues

---

webserver/Dockerfile
webserver/html/ropewiki/LocalSettings.php

Purging the google Analytics code & config.
It doesn't work with newer versions of mediawiki (I'm working on upgrades), is in accurate with cloudflare sat in front of it, is creepy (and illegal without opt-in in a number of places), and as far as I'm aware no one looks at.
bye bye.

Remove googleAnalytics extension & config

---

deploy_tool.py
docker-compose.yaml
webserver/Dockerfile

Fixes a bunch of stuff we're being warned about when running "dc build"....
- docker compose "version" no longer needed and should be removed.
- docker env should use "="
- python datetime "now" utc warnings
- python format parameters provides but not used
All tested locally.

Fix minior deployment related warnings

---

webserver/Dockerfile
webserver/fpm-pool.conf
webserver/nginx/sites-enabled/ropewiki.com
webserver/scripts/system_start.sh

To make future upgrades simpler this defines the Mediawiki & PHP versions as variables which are used throughout the Dockerfile.
It also makes version agnostic paths (e.g `/etc/php/current/...`) which means versions changes don't required changes elsewhere (e.g. nginx configs).
It also deletes redundant php-fpm config from `system_start.sh`, as that's handled by a dedicated `fpm-pool.conf` file.

MW & PHP version variables

---

webserver/Dockerfile
webserver/html/ropewiki/composer.json

---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/RopeWiki/app/pull/55).
* #105
* #104
* __->__ #55
* #103

SMW 2.1 -> 2.5.8

---

webserver/Dockerfile
webserver/html/ropewiki/kml_to_gpx.php

The luca server has become very unreliable. Let's stop using it for stuff we don't need to.
This setups a replace for the `/luca/rwr?gpx` endpoint which does kml -> gpx conversion.
A POST request is sent to `https://ropewiki.com/kml_to_gpx.php` with the file_path parameter, which is the local on disk path to the KML file. It responds with the converted data.
This branch is already active to the production site, so you can test directly again ropewiki.com
After this is committed I'll update links to the old path (mostly in common.js I think).
```
~$ curl -X POST -d "file_path=/rw/images/d/d7/Estaron.kml" https://ropewiki.com/kml_to_gpx.php
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.0" creator="GPSBabel - http://www.gpsbabel.org" xmlns="http://www.topografix.com/GPX/1/0"> …
```

[Deprecate luca server] Create a kml to gpx converter in php

---

webserver/html/ropewiki/kml_to_gpx.php

Attempt 2 at making the gpx converter run on the webserver not the luca server.
The "download gpx" link in `Template:KMLDisplay` is already updated to point to this.
Tested locally and then switched branches in prod for easy testing for others:
Try clicking "download gpx" under the map on any canyon, should take you to:
https://ropewiki.com/kml_to_gpx.php?url=https://ropewiki.com/images/a/ab/Heaps_Canyon.kml

Fixes to kml_to_gpx.php - works with mediawiki now.

---

webserver/Dockerfile
webserver/fpm-pool.conf

- MW 1.27.1 -> 1.27.7
- PHP 5.6 -> 7.1
Small upgrade of mediawiki LTS version in order to unlock more significant PHP upgrade required for the next SMW upgrade.
Local testing, then branch checked out on the production site after the 1.27.1 upgrade since no schema changes needed.
Versions confirmed here: https://ropewiki.com/Special:Version

PHP 7.1 & MW 1.27.7

---

webserver/Dockerfile
webserver/html/ropewiki/LocalSettings.php

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118
Summary:
Looks like these settings were manually overwritten in the past, but not ported to docker, so got lost after an upgrade.
---
Test Plan:
After a container rebuilt expected config is in place:
```
root@ropewiki_webserver:/# grep -E '(egMapsCoordinateNotation|egMapsCoordinateDirectional)' /rw/extensions/Maps/Maps_Settings.php
$GLOBALS['egMapsCoordinateNotation'] = Maps_COORDS_FLOAT;  # Ropewiki override
$GLOBALS['egMapsCoordinateDirectional'] = false;  # Ropewiki override
```
---
---

Fix coords

---

webserver/html/ropewiki/LocalSettings.php

This PR re-enables the captcha for creating new accounts.  Verified in prod to show the captcha and reject creation attempts when not answered.

Re-enable captcha

---

reverse_proxy/blockips.conf

Scrapy is a scraping tooling someone was using to hammer the site.
I've manually edited the production nginx config to enable this already, load has dropped and the requests are all logging HTTP 444.

Add Scrapy to user-agent blocklist

---

webserver/Dockerfile
webserver/html/ropewiki/LocalSettings.php
webserver/html/ropewiki/extensions/SemanticMediaWiki/.smw.json

This is a significant upgrade. It's paired with matching `maps`, `semantic-results formats`, and `SemanticDrilldown` upgrades.
**General notes:**
- The upgraded `semantic results format` is needed in order to provide the `array` type of result format used in many pages.
- new `semantic results format` also needed slideshow query changed - already fixed in master.
**Important note:**
- The database schema upgrade process is *long*. The `rebuildData.php` process takes ~19hr on my 8 core dev machine. (Update: I don't think the site needs to be offline/read-only that long - WIP).
- the `.smw.json` file needs to be place *after* the database upgrade, but it's stored in this commit because logically it needs to be paired with these versions.
The plan is to do the upgrade offline using a copy of …

SMW 2.5.8 -> 3.0.2

---

webserver/Dockerfile

Nothing major, house keeping basically related to SphinxSearch:
- SphinxSearch is now installed in the same way as other extensions available on github, and also tracks `$MW_REL_BRANCH`
- We use the extension's `composer install` support to automatically install the API file needed - rather than manually installing. Despite the comment saying we need a different version, I can't find any differences between the files. (Step 6.1 here says they're the same too: https://www.mediawiki.org/wiki/Extension:SphinxSearch#9).
Ran locally, sphinx is happily running & search is functioning.

web dockerfile tweaks

---

webserver/Dockerfile

Arhg. This was correct, then I quickly decided to sort the list alphabetically, and docker build caching didn't trigger the issue.

[hotfix] - fix broken line wrapping

---

webserver/Dockerfile

This is needed by PDFHandler, example: `[[File:Urumbilum_Canyon.pdf]]`
**Before**
```
Error creating thumbnail: /bin/bash: line 1: /usr/bin/gs: No such file or directory convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/581. convert: no images defined `/tmp/transform_353c5b110b90.jpg' @ error/convert.c/ConvertImageCommand/3234.
```
**After**
PDF appears inline:

add ghostscript

---

webserver/html/ropewiki/LocalSettings.php

This lets the `DISPLAYTITLE` magic word free rein to change the displayed page title (rather than just the text case currently).
Will use it on a few pages like Main Page to improve the welcome message.

$wgRestrictDisplayTitle = false

---

webserver/html/ropewiki/LocalSettings.php

Going to use this inbuilt extension to add more appealing search boxes to the site.
Manually enabled in production to confirm it works with live version (my dev environment is a version ahead).
https://ropewiki.com/Special:Version
Sneak peak of new design I'm working on (not finalized)....

enable InputBox
